// Code generated by "stringer -type=transport transport.go"; DO NOT EDIT.

package mgrpc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[tHTTP_POST-0]
	_ = x[tWebSocket-1]
	_ = x[tPlainTCP-2]
	_ = x[tSerial-3]
	_ = x[tMQTT-4]
	_ = x[tAzureDM-5]
	_ = x[tGCP-6]
	_ = x[tWatson-7]
	_ = x[tUDP-8]
	_ = x[tExternal-9]
}

const _transport_name = "tHTTP_POSTtWebSockettPlainTCPtSerialtMQTTtAzureDMtGCPtWatsontUDPtExternal"

var _transport_index = [...]uint8{0, 10, 20, 29, 36, 41, 49, 53, 60, 64, 73}

func (i transport) String() string {
	if i < 0 || i >= transport(len(_transport_index)-1) {
		return "transport(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _transport_name[_transport_index[i]:_transport_index[i+1]]
}
